export {default as Contact} from './contact/Contact'
export {default as Header} from './header/Header'
export {default as Navbar} from './navbar/Navbar'
export {default as Project} from './project/Project'
export {default as Tech} from './tech/Tech'